h8r-dev/stacks

chain/framework/helm/helm.cue
=> feat: add service output

chain/registry/github/github.cue, chain/registry/github/input.cue, chain/scm/github/create-github-repo.sh, chain/supply/cd/cd.cue, chain/supply/tools/output.cue, chain/tools/argocd/create-apps.sh, cuelib/network/ingress/ingress.cue
=> fix: cue bug fix

.github/workflows/ci.yaml
Run workflow pull_request if it is not a fork, as pull_request_target if it is a fork.
=> ci: select events to trigger workflows

chain/framework/gin/template/routers/router.go
=> feat: add some metrics into framework/gin

chain/components/cd/argocd/create-apps.sh
=> fix: create prometheus ns

chain/components/addons/nocalhost/_helpers.tpl, chain/components/addons/nocalhost/copy.sh, chain/components/addons/nocalhost/ingress.yaml, chain/components/addons/nocalhost/nocalhost.cue, chain/internal/dev/nocalhost/init.cue, chain/internal/dev/nocalhost/install.cue, chain/internal/dev/nocalhost/nocalhost.cue, official-stack/gin-next/plans/plan.cue
- init nocalhost
- add nocalhost ingress
=> refactor: init nocalhost

official-stack/gin-next/schemas/schema.yaml, official-stack/gin-vue/schemas/schema.yaml, official-stack/sample/schemas/schema.yaml, official-stack/spring-vue/schemas/schema.yaml
=> fix: remove APP_NAME in schemas

chain/components/addons/prometheus/copy.sh, chain/components/cd/argocd/create-apps.sh, chain/components/framework/gin/dashboards/gin-dashboard-annotations.json, chain/components/framework/gin/dashboards/gin-dashboard-output-hook.json, chain/components/framework/gin/dashboards/gin-dashboard.yaml
=> feat: output grafana dashboard

chain/internal/cd/argocd/argocd.cue
=> fix: argocd patch and wait

chain/components/addons/prometheus/copy.sh, chain/components/framework/spring/dashboards/spring-boot-dashboard-annotations.json, chain/components/framework/spring/dashboards/spring-boot-dashboard.yaml, chain/components/framework/spring/spring.cue, chain/components/framework/spring/template/pom.xml, chain/components/framework/spring/template/src/main/resources/application.yaml, chain/components/framework/spring/test/test.cue, official-stack/spring-vue/plans/plan.cue
=> Spring service monitor

chain/components/addons/prometheus/copy.sh
=> fix: check if annotations exist

chain/components/framework/helm/helm.cue, chain/components/framework/helm/input.cue, chain/components/framework/spring/template/src/main/resources/application.yaml, chain/factory/scaffoldfactory/input.cue, chain/factory/scaffoldfactory/scaffold.cue, official-stack/gin-next/plans/plan.cue, official-stack/gin-vue/plans/plan.cue, official-stack/remix/plans/plan.cue, official-stack/sample/plans/plan.cue, official-stack/spring-vue/plans/plan.cue
- helm input add `appName` `ingressHostPath` `rewriteIngressHostPath` field
- helm starter support version
- backend stack ingress path default  setting to `/api`
- spring-vue remove nocalhost addons
- fix the spring swagger URL
=> feat: scaffold and helm

chain/components/addons/nocalhost/input.cue, chain/components/dev/nocalhost/input.cue, chain/components/dev/nocalhost/nocalhost.cue, chain/components/utils/kubeconfig/main.cue, chain/components/utils/kubeconfig/output.cue, chain/internal/dev/nocalhost/init.cue, chain/internal/dev/nocalhost/nocalhost.cue, official-stack/gin-next/plans/plan.cue
nocalhost/nocalhost#1317
nocalhost/nocalhost#1319
nocalhost/nocalhost.github.io#204
=> fix: add nocalhost extra api server

chain/components/addons/loki/copy.sh, chain/components/addons/loki/input.cue, chain/components/addons/loki/loki.cue, chain/components/addons/nocalhost/copy.sh, chain/components/addons/nocalhost/input.cue, chain/components/addons/nocalhost/nocalhost.cue, chain/components/addons/prometheus/copy.sh, chain/components/addons/prometheus/input.cue, chain/components/addons/prometheus/prometheus.cue, chain/components/origin/origin.cue, chain/factory/scaffoldfactory/input.cue, chain/factory/scaffoldfactory/scaffold.cue, official-stack/gin-next/plans/plan.cue, official-stack/gin-vue/plans/plan.cue, official-stack/remix/plans/plan.cue, official-stack/sample/plans/plan.cue, official-stack/spring-vue/plans/plan.cue, scripts/internal/argocd/deploy.yaml, scripts/internal/ingress-nginx/deploy.yaml
Usage: NETWORK_TYPE=internal | global
Download helm chart from official repository or CODING.NET repository.
=> feat: internal network support

chain/components/addons/prometheus/copy.sh
=> feat: add prometheus and alertmamager basic auth

chain/components/framework/gin/template/routers/common_router.go
=> feat: return msg for gin url root path

chain/components/ci/github/input.cue, chain/components/framework/helm/helm-create-merge.sh, chain/components/framework/helm/helm.cue, chain/components/framework/helm/input.cue, chain/components/registry/github/github-registry.sh, chain/components/registry/github/github.cue, chain/components/registry/github/input.cue, chain/factory/scaffoldfactory/scaffold.cue
application helm chart move to parent chart
eg: appName=myapp stack=spring-vue
```
myapp
| Chart.yaml
| charts
| myapp-backend
| Chart.yaml
| values.yaml
| templates
| myapp-frontend
| Chart.yaml
| values.yaml
| templates
```
=> refactor: helm sub charts

chain/components/framework/helm/helm.cue, chain/components/framework/remix/dashboards/remix-dashboard-annotations.json, chain/components/framework/remix/dashboards/remix-dashboard.yaml, chain/components/framework/remix/remix.cue, chain/components/utils/organization/organization.cue, official-stack/sample/README.md, official-stack/sample/metadata.yaml, official-stack/sample/plans/plan.cue, official-stack/sample/schemas/schema.yaml, official-stack/sample/test/repo_test.go
1. User only input `GitHub token`, `KubeConfig`, other parameters hard-coded.
2. Set framework to be `remix`.
3. Persist Sqlite data of the remix app on a K8S PVC
4. Optimize default ui of Remix app.
5. Collect app metrics
=> Migrate sample to remix

chain/components/framework/helm/helm-create-merge.sh, chain/internal/dev/nocalhost/nocalhost.cue, official-stack/gin-next/plans/plan.cue
=> fix: nocalhost config

chain/components/addons/nocalhost/copy.sh, chain/components/addons/prometheus/copy.sh, chain/components/cd/argocd/create-apps.sh, chain/components/framework/helm/helm-create-merge.sh
=> fix: add http schema

chain/components/addons/prometheus/copy.sh
=> feat: add alert rule

chain/components/addons/prometheus/copy.sh
=> fix: set alert threshold to 1

chain/components/addons/loki/copy.sh, chain/components/addons/nocalhost/copy.sh, chain/components/addons/prometheus/copy.sh, chain/factory/scaffoldfactory/input.cue, official-stack/gin-next/plans/plan.cue, official-stack/gin-vue/plans/plan.cue, official-stack/sample/plans/plan.cue, official-stack/spring-vue/plans/plan.cue
=> feat: rename network type to china_network

chain/internal/dev/nocalhost/nocalhost.cue
=> fix: add nocalhost team user suffix

chain/components/ci/github/create-workflow.sh, chain/components/ci/github/create.sh, chain/components/ci/github/github.cue, chain/components/ci/github/input.cue, chain/components/ci/github/template/docker-publish.yaml, chain/components/ci/github/test/test.cue, chain/components/registry/github/github-registry.sh, chain/components/registry/github/github.cue, chain/components/registry/github/input.cue
Features:
1. Support release new updates by pushing code to `main` branch
=> Feat: support release new updates by pushing code to main branch.

official-stack/dotnet-react-dapr/metadata.yaml, official-stack/gin-next/metadata.yaml
=> fix: metadata stack name

.github/workflows/ci.yaml
=> ci: cleanup GitHub repositories and packages

chain/components/addons/prometheus/create.sh, official-stack/gin-next/plans/plan.cue
=> fix: configure serviceMonitor for gin framework

chain/components/addons/prometheus/create.sh
=> fix: only select alert rules created by stacks

chain/components/addons/prometheus/create.sh, chain/components/framework/gin/dashboards/gin-dashboard-annotations.json, chain/components/framework/gin/dashboards/gin-dashboard-annotations.yaml, chain/components/framework/spring/dashboards/spring-boot-dashboard-annotations.json, chain/components/framework/spring/dashboards/spring-boot-dashboard-annotations.yaml
=> fix: support multi dashboards

chain/components/framework/helm/helm-create-merge.sh, official-stack/dotnet-react-dapr/plans/plan.cue, official-stack/gin-next/plans/plan.cue, official-stack/gin-vue/plans/plan.cue, official-stack/sample/plans/plan.cue, official-stack/spring-vue/plans/plan.cue
User can set repo visibility via env `REPO_VISIBILITY`
=> feat: add repo visibility env

.github/workflows/ci.yaml
=> ci: change repo visibility to public

chain/components/ci/github/template/docker-publish.yaml
=> fix: add image tag

chain/components/addons/nocalhost/input.cue
nocalhost/nocalhost#1330
nocalhost/nocalhost#1327
nocalhost/nocalhost.github.io#209
=> fix: update nocalhost version

cuelib/stacks/stack.cue, official-stack/wip-gin-next/plans/plan.cue
=> fix: stacks path

cuelib/framework/gin/config.cue, cuelib/framework/gin/init.cue, cuelib/framework/next/config.cue, cuelib/framework/next/init.cue
=> refactor: use base image

cuelib/framework/framework.cue, cuelib/stacks/stack.cue
=> refactor: change framework path

cue.mod/module.cue, scripts/process_stacks.sh
=> refactor: quik vendor

cuelib/scm/github/create-github-repo.sh, cuelib/scm/github/github.cue, cuelib/scm/github/terraform/main.tf, cuelib/scm/github/terraform/provider.tf, cuelib/scm/github/terraform/variables.tf, cuelib/scm/github/test/README.md, cuelib/scm/github/test/test.cue, cuelib/stacks/stack.cue
=> refactor: push code to github

cuelib/scm/github/github.cue, cuelib/scm/github/test/test.cue, cuelib/stacks/stack.cue
=> refactor: add scm/github test case

cuelib/component/framework/helm/create.cue, cuelib/component/framework/helm/create.sh, cuelib/component/framework/helm/test/test.cue, cuelib/internal/base/base.cue
=> refactor: add helm create fun

.github/workflows/ci.yaml
=> ci: add network type

cuelib/component/ci/add-workflow.cue, cuelib/component/deploy/init.cue, cuelib/component/framework/gin/init.cue, cuelib/component/framework/helm/craete-parent-chart.sh, cuelib/component/framework/helm/create.cue, cuelib/component/framework/helm/create.sh, cuelib/component/framework/helm/parent-chart.cue, cuelib/component/framework/helm/test/test.cue, cuelib/component/framework/next/init.cue, cuelib/internal/base/base.cue, cuelib/stack/stack.cue
=> refactor: create parent helm chart

cuelib/component/scm/github/github.cue, cuelib/stack/stack.cue
=> refactor: push framework codes

cuelib/component/cd/argocd/argocd.cue, cuelib/component/cd/argocd/create-app.sh, cuelib/component/cd/argocd/test/test.cue, cuelib/component/deploy/init.cue, cuelib/internal/base/base.cue, cuelib/stack/stack.cue
=> refactor: add argocd

cuelib/internal/utils/echo/echo.cue, cuelib/internal/utils/echo/echo.sh, cuelib/internal/var/var.cue, cuelib/stack/stack.cue
=> refactor: manage variables

cuelib/component/deploy/helm/encrypt-secret.sh, cuelib/component/framework/gin/config.cue, cuelib/internal/addon/addon.cue, cuelib/internal/addon/read-config.sh, cuelib/internal/utils/echo/echo.cue, cuelib/stack/stack.cue
=> refactor: read configmap

cuelib/internal/addon/addon.cue, cuelib/internal/addon/read-config.sh, cuelib/stack/stack.cue
=> Revert "refactor: convert ConfigMap contents into cue"

cuelib/component/cd/argocd/argocd.cue, cuelib/component/cd/argocd/create-app.sh, cuelib/component/cd/argocd/test/test.cue, cuelib/component/deploy/init.cue, cuelib/internal/addon/addon.cue, cuelib/internal/addon/read-config.sh, cuelib/stack/stack.cue
=> refactor: use infra config

.github/workflows/upload-stack.yml, Makefile, scripts/pack-infra.sh
=> refactor: update infra stack

chain/v3/component/deploy/helm/encrypt-secret.sh, infra/plan/plan.cue
=> refactor: change sealed-secrets config ns, change argocd install ns

chain/v3/component/deploy/init.cue, chain/v3/internal/var/var.cue
=> refactor: rewrite ingress for backend

chain/components/infra/cd/argocd/argocd.cue, chain/components/infra/cd/argocd/create.sh, chain/components/infra/cd/argocd/input.cue, chain/components/infra/dapr/create.sh, chain/components/infra/heighliner/dashboard/create.sh, chain/components/infra/heighliner/dashboard/dashboard.cue, chain/components/infra/heighliner/dashboard/input.cue, chain/components/infra/heighliner/dashboard/output.cue, chain/components/infra/prometheus/create.sh, chain/components/infra/sealedSecrets/create.sh, chain/components/origin/origin.cue, chain/internal/cd/argocd/argocd.cue, infra/plan/plan.cue, official-stack/wip-gin-next/cue.sums
=> fix: helm install infra component

chain/components/infra/cd/argocd/argocd.cue
=> fix: add dagger import

chain/components/infra/cd/argocd/argocd.cue
=> fix: patch argocd

scripts/process_stacks.sh
=> fix: ci linter cue check

official-stack/wip-gin-next/metadata.yaml, official-stack/wip-gin-next/schemas/schema.yaml
=> fix: wip stack schema.yaml and metadata.yaml

chain/components/infra/state/config.yaml, chain/components/infra/state/manage.cue, chain/components/infra/state/set-config.sh, chain/components/infra/state/test/test.cue, infra/plan/plan.cue
=> feat: add infra config

chain/v3/component/repository/repository.cue, chain/v3/stack/stack.cue
=> refactor: move creating repo code out from stack

chain/v3/component/deploy/helm/encrypt-secret.cue, chain/v3/component/deploy/helm/install-or-upgrad.cue, chain/v3/component/deploy/helm/install-or-upgrade.sh, chain/v3/component/deploy/helm/test/test.cue
=> feat: helm install local chart

chain/v3/component/deploy/helm/craete-parent-chart.sh, chain/v3/component/deploy/helm/create-chart.sh, chain/v3/component/deploy/helm/install-or-upgrad.cue, chain/v3/component/deploy/helm/test/test.cue, chain/v3/component/deploy/init.cue, chain/v3/component/repository/repository.cue, chain/v3/stack/stack.cue
=> feat: add dev environment

chain/components/infra/heighliner/dashboard/create.sh, chain/components/infra/loki/create.sh, chain/components/infra/prometheus/create.sh, chain/components/infra/sealedSecrets/create.sh
=> feat: add force install helm chart

chain/v3/component/deploy/helm/create-chart.cue, chain/v3/component/deploy/init.cue
=> feat: add app domain

chain/v3/component/cd/argocd/argocd.cue, chain/v3/component/deploy/init.cue, chain/v3/component/repository/repository.cue, chain/v3/internal/state/writer.cue, chain/v3/pkg/wait/test/test.cue, chain/v3/pkg/wait/wait-list.cue, chain/v3/stack/stack.cue
=> feat: create dev environments after repos push

chain/v3/internal/state/writer.cue
Signed-off-by: Jinming Guo <vgjm456@qq.com>
=> fix: store crds in "heighliner" namespace

chain/components/infra/heighliner/dashboard/create.sh, chain/components/infra/heighliner/dashboard/dashboard.cue, chain/factory/basefactory/base.cue
=> feat: set dashboard hosts

chain/components/infra/state/config.yaml
=> feat: set configmap dashboard ingress

chain/v3/component/deploy/helm/create-chart.sh
Signed-off-by: Jinming Guo <vgjm456@qq.com>
=> hot-fix: change app domain

chain/v3/internal/state/writer.cue
Signed-off-by: Jinming Guo <vgjm456@qq.com>
=> hot-fix: correct dev environment domain

chain/components/infra/loki/create.sh, chain/components/infra/prometheus/create.sh
=> fix: grafana default datasource

chain/v3/component/deploy/helm/install-or-upgrad.cue, chain/v3/component/deploy/helm/install-or-upgrade.sh, chain/v3/component/deploy/helm/test/test.cue
Migrating infra to v3 will use the helm install flag `--values`
=> feat: support helm install values

chain/v3/pkg/kubectl/apply.cue, chain/v3/pkg/kubectl/apply.sh, chain/v3/pkg/kubectl/test/test.cue
Support manifest yaml/json, url, fs in the same function `#Apply`
=> feat: Implement kubectl apply

chain/v4/stack/stack.cue
=> fix: import

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> chore: chang cue format

.github/workflows/lint.yaml
=> ci: all pr will be lint checked

.github/workflows/ci.yaml
=> ci: set feishu bot secret

chain/v4/internal/base/base.cue, chain/v4/pkg/k8s/helm/install-or-upgrad.cue, chain/v4/pkg/k8s/helm/install-or-upgrade.sh, chain/v4/pkg/k8s/helm/test/test.cue, chain/v4/pkg/k8s/kubeconfig/main.cue, chain/v4/pkg/k8s/kubeconfig/run.sh, chain/v4/pkg/k8s/kubectl/apply.cue, chain/v4/pkg/k8s/kubectl/apply.sh, chain/v4/pkg/k8s/kubectl/test/test.cue
- `base.#Image` "github.com/h8r-dev/stacks/chain/v4/internal/base"
- `kubeconfig.#TransformToInternal` "github.com/h8r-dev/stacks/chain/v4/pkg/k8s/kubeconfig"
- `helm.#InstallOrUpgrade` "github.com/h8r-dev/stacks/chain/v4/pkg/k8s/helm"
- `kubectl.#Apply` "github.com/h8r-dev/stacks/chain/v4/pkg/k8s/kubectl"
=> feat(v4): add public pkg

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): add app domain

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): add app image config

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): fill the app config file

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): change app repo config

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): add app deploy config

chain/v3/component/cd/argocd/argocd.cue, chain/v3/component/scm/github/create-repo.cue, chain/v4/deploy/chart/craete-parent-chart.sh, chain/v4/deploy/chart/create-chart.cue, chain/v4/deploy/chart/create-chart.sh, chain/v4/deploy/chart/create-parent-chart.cue, chain/v4/deploy/chart/encrypt-secret.cue, chain/v4/deploy/chart/encrypt-secret.sh, chain/v4/deploy/chart/test/test.cue, chain/v4/deploy/init.cue, chain/v4/deploy/test/app.cue, chain/v4/deploy/test/test.cue, chain/v4/internal/var/var.cue
=> feat(v4): deploy init

chain/v4/forkenv/bash/add-values-file-and-env.sh, chain/v4/forkenv/bash/push-env.sh, chain/v4/forkenv/forkenv.cue, official-stack/forkenv/plans/app.cue, official-stack/forkenv/plans/app.yaml, official-stack/forkenv/plans/plan.cue
```
actions:
up:
args:
service:
- name: forkmain-backend
type: backend
url: https://github.com/lyzhang1999/forkmain-backend
env: 
- name: KEY
value: VALUE
- name: forkmain-frontend
type: frontend
url: https://github.com/lyzhang1999/forkmain-frontend
env: 
- name: KEY
value: VALUE
deploy:
name: forkmain-deploy
url: https://github.com/lyzhang1999/forkmain-deploy
forkenv:
name: bug-fix
from: main
domain: bug-fix.hello-world36.h8r.site
scm:
name: github
type: github
organization: h8r-dev
```
=> Forkenv stack

chain/v4/cd/argocd/application-set.cue, chain/v4/cd/argocd/application-set.sh, chain/v4/cd/argocd/application-set.yaml, chain/v4/cd/argocd/test/test.cue, chain/v4/deploy/init.cue
=> feat(v4): add argocd applicationset

chain/v4/deploy/chart/craete-parent-chart.sh
=> feat(v4): add parent chart values

chain/v4/service/dockerfile/template/go.yaml, chain/v4/service/repository/repository.cue, chain/v4/service/service.cue, chain/v4/stack/stack.cue, official-stack/microservice/plans/plan.cue
=> fix: take env inputed github token

chain/v4/deploy/init.cue, chain/v4/stack/stack.cue
=> feat(v4): add deploy init to stack

chain/v4/service/dockerfile/template/go.t
=> fix: modify dockerfile template workdir

chain/v4/service/dockerfile/template/go.t
=> fix: add config file for gin service

official-stack/forkenv/plans/app.cue, official-stack/forkenv/plans/app.yaml, official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): update config

chain/v4/forkenv/bash/add-values-file-and-env.sh
=> feat: remove cat values.yaml

chain/v4/forkenv/bash/push-env.sh
=> feat: patch ApplicationSet timestamp

chain/v4/pkg/git/git.cue
=> fix: always pull source code

official-stack/microservice/plans/app.cue, official-stack/microservice/plans/app.yaml
=> feat(v4): add ingress path parameter to app config

.gitignore
=> feat: ignore input.cue files

Makefile, scripts/process_stacks.sh
=> feat: make link makes softlink for chain dir

chain/v4/deploy/init.cue
=> feat(v4): remove applicationSet

.gitignore, chain/v4/forkenv/bash/add-values-file-and-env.sh, chain/v4/forkenv/forkenv.cue
=> feat: support fork from each repository and add cluster key

official-stack/forkenv/plans/app.cue
=> feat: add app.cue to generate app.yaml

chain/v4/pkg/git/push.sh
=> fix: detect if push is needed when rerun stack

chain/v4/pkg/git/git.cue, chain/v4/pkg/git/pr.sh, chain/v4/service/service.cue
=> feat(v4): pr instead of push when the repo already exists

chain/v4/deploy/chart/create-chart.cue, chain/v4/deploy/chart/create-chart.sh, chain/v4/deploy/chart/ingress.cue, chain/v4/deploy/chart/test/test.cue, chain/v4/deploy/init.cue
=> feat(v4): set ingress paths

chain/v4/service/dockerfile/template/ts.t
=> fix(v4): change node pod user

chain/v4/stack/stack.cue, chain/v4/update/test/test.cue, chain/v4/update/update.cue, chain/v4/update/update.sh
=> feat(v4): support update env and ingress

chain/v4/cd/argocd/argocd.cue, chain/v4/cd/argocd/create-app.sh, chain/v4/deploy/init.cue, chain/v4/forkenv/forkenv.cue
=> feat: specify target namespace

chain/v4/deploy/init.cue, chain/v4/middleware/chart.sh, chain/v4/middleware/middleware.cue, chain/v4/middleware/test/test.cue, chain/v4/stack/stack.cue
=> feat(v4): support middleware pg

chain/v4/cd/argocd/argocd.cue, chain/v4/deploy/chart/test/test.cue, chain/v4/deploy/test/test.cue, chain/v4/internal/addon/addon.cue, chain/v4/internal/addon/read-config.sh, chain/v4/internal/echo/echo.cue, chain/v4/internal/echo/echo.sh, chain/v4/internal/kubeconfig/main.cue, chain/v4/internal/kubeconfig/run.sh, chain/v4/pkg/git/git.cue, chain/v4/service/dockerfile/generate.cue, chain/v4/service/repository/repository.cue, chain/v4/service/service.cue, chain/v4/service/workflow/generate.cue, chain/v4/stack/stack.cue
=> fix: v4 stack remove v3 package dependency

chain/v4/forkenv/bash/add-values-file-and-env.sh, chain/v4/forkenv/forkenv.cue
=> feat: support update env

chain/v4/service/dockerfile/generate.cue, chain/v4/service/service.cue
=> hot-fix: doesn't require entryFile if scaffold is true

chain/v4/deploy/chart/create-chart.cue, chain/v4/deploy/chart/create-chart.sh, chain/v4/deploy/chart/test/test.cue, chain/v4/deploy/init.cue
=> feat: supports custom ports

chain/v4/forkenv/forkenv.cue, official-stack/forkenv/plans/app.cue
=> feat: Modify the app.yaml data structure

chain/v4/service/dockerfile/template/nextjs.t
=> hot-fix: nextjs dockerfile listen on port 3000

chain/v4/middleware/middleware.cue
=> feat: fix fullnameOverride

chain/v4/service/code/gin/main.go
=> chore: typo

chain/v4/forkenv/bash/add-values-file-and-env.sh
=> feat: overwrite env

chain/v4/internal/var/var.cue
=> feat: uses h8r-dev/helm-starter main branch

chain/v4/deploy/init.cue
=> feat: fullname override by service name

chain/v4/service/workflow/template/docker-publish.yaml
=> fix: update main deploy env values.yaml

chain/v5/service/dockerfile/generate.cue, chain/v5/service/dockerfile/test/test.cue
=> fix: rename front-end keys

chain/v5/service/dockerfile/template/static.conf.t, chain/v5/service/dockerfile/test/test.cue
=> fix: rename Single-Page App to SPA

chain/v4/pkg/git/pr.sh
=> feat: fix gitignore

chain/v5/service/dockerfile/template/gin.t
=> feat: gin dockerfile remove noroot constraint

chain/v5/deploy/init.cue, chain/v5/service/code/framework.cue
=> fix: frontend static use new starter path

official-stack/microservice/plans/plan.cue
=> release: v5 support new frontend input form

chain/v5/pkg/git/pr.sh, chain/v5/service/workflow/template/docker-publish.yaml
=> feat: git ignore and workflows
